### ISSUE TITLE
Host a Home Assistant Add-On in this repo?

### ISSUE THREAD

**Issue by ivmarkov** [kk7ds/pynx584#72]
Not a bug really - but JFYI - I just published a very simple Home Assistant Add-On for this server: https://github.com/ivmarkov/nx584

You might consider hosting it here, in this repo.

**Comment by kk7ds** [comment]
I haven't used HA in years, so I'm not familiar with this. Looks like it's just a structured git repo that HA knows how to grab in order to install components? It also looks like you expect people to fork it for their own configuration. I certainly can fork it here, but it seems better to let you keep it, especially if you're going to maintain it (because I am not). Is there some reason to keep it in my namespace near pynx584 itself?

Maybe this issue should turn into a PR mentioning your repo in the README?

**Comment by ivmarkov** [comment]
Yes, it is just a structured git repo. If you don't feel like maintaining it, it is OK to stay in my personal org. Adding a reference to it from your README might indeed help folks find it out. If pynx584 is supposed to be used with HA, an add-on is pretty much the norm these days, as it is the easiest way to set it up and make sure it is running OK in the long run. 

(As for forking for their own configuration - that's only because the current add-on does not expose ways to configure it. I might fix that in future.)

**Comment by kk7ds** [comment]
Sorry, I replied to this via email and see that it never got posted here.

Can you submit a PR for a README update that points to your repo with the right words? I can do it, but I think it'd be better if you wordsmith it...if you're willing.

**Comment by kk7ds** [comment]
Okay, do you want to write up the change to the readme as a PR here? If not I can do it later, but I'll want you to look at it to make sure it makes sense 🙂
________________________________

**Comment by ivmarkov** [comment]
Sounds like a plan - I'll review your additions to the readme.

**Comment by juanjoSanz** [comment]
I have improved @ivmarkov repo, mine is configurable from Home Assistant Add-on directly.  

https://github.com/juanjoSanz/home-assistant-addons/tree/main/nx584

**Comment by txwindsurfer** [comment]
@juanjoSanz I just want to report that I installed your improved @ivmarkov repo on my HAOS system, and it is working.  I know you indicated not to install in a production environment but that is how I installed with a backup running on an RPI so I can always just move the serial cable.  Thank you for you work on this!  You have at least 1 happy user.

**Comment by juanjoSanz** [comment]
> @juanjoSanz I just want to report that I installed your improved @ivmarkov repo on my HAOS system, and it is working. I know you indicated not to install in a production environment but that is how I installed with a backup running on an RPI so I can always just move the serial cable. Thank you for you work on this! You have at least 1 happy user.

Thanks for the feedback, the msg about "not to use in a production environment" is not part of the HASS Add-on.

**Comment by Pre10der** [comment]
@juanjoSanz - question re. Config inside HA. I note you have configured your Zones config to be comma separated. Say you have a panel with  a larger number of max zones (e.g. 128 in my case), and the active zones operate on different and non-contiguous zone numbers (many of which are blank)…how would this work in the config?

Example config.ini entry:
[config]
max_zones = 128

[zones]
1 = Main Room
2 = Bathroom
3 = Lounge Room
4 = Hallway
9 = Hallway 2
10 = Bedroom 1
11 = Bedroom 2
12 = Garage
17 = Bedroom 3
19 = Bedroom 4

**Comment by Pre10der** [comment]
You can ignore this now. I have this add-on working correctly in my environment. The resolution to my issue below was to simply have blank entries in the CSV value for the Zones tank entry (e.g. zone1,zone2,,,zone5).

I now have this running in my environment. 

The only issue is that being an add-on, there is a timing issue where HASS may have started before the add-on is started. Upon a full HASSOS reboot, a subsequent HA restart is required…at least in my case. 

Because of this, it may warrant a completely seperate container or VM….regardless, I am happy with this. It is one less piece of hardware running in my home having decomm’d the old RPiv1 it has running on for the last 6yrs!


> [@juanjoSanz](https://github.com/juanjoSanz) - question re. Config inside HA. I note you have configured your Zones config to be comma separated. Say you have a panel with a larger number of max zones (e.g. 128 in my case), and the active zones operate on different and non-contiguous zone numbers (many of which are blank)…how would this work in the config?
> 
> Example config.ini entry: [config] max_zones = 128
> 
> [zones] 1 = Main Room 2 = Bathroom 3 = Lounge Room 4 = Hallway 9 = Hallway 2 10 = Bedroom 1 11 = Bedroom 2 12 = Garage 17 = Bedroom 3 19 = Bedroom 4

**Comment by juanjoSanz** [comment]
> You can ignore this now. I have this add-on working correctly in my environment. The resolution to my issue below was to simply have blank entries in the CSV value for the Zones tank entry (e.g. zone1,zone2,,,zone5).
> 
> I now have this running in my environment.
> 
> The only issue is that being an add-on, there is a timing issue where HASS may have started before the add-on is started. Upon a full HASSOS reboot, a subsequent HA restart is required…at least in my case.
> 
> Because of this, it may warrant a completely seperate container or VM….regardless, I am happy with this. It is one less piece of hardware running in my home having decomm’d the old RPiv1 it has running on for the last 6yrs!
> 
> > [@juanjoSanz](https://github.com/juanjoSanz) - question re. Config inside HA. I note you have configured your Zones config to be comma separated. Say you have a panel with a larger number of max zones (e.g. 128 in my case), and the active zones operate on different and non-contiguous zone numbers (many of which are blank)…how would this work in the config?
> > Example config.ini entry: [config] max_zones = 128
> > [zones] 1 = Main Room 2 = Bathroom 3 = Lounge Room 4 = Hallway 9 = Hallway 2 10 = Bedroom 1 11 = Bedroom 2 12 = Garage 17 = Bedroom 3 19 = Bedroom 4

Sorry, I didn't see your message until now. 

The issue of add-on not starting before HASS integration is also happening to me, unfortunately it is probably due to lack of retry process in nx584 integration, which is legacy.

**Comment by txwindsurfer** [comment]
Just FYI, I use this automation to address the lack of retry process:
```
alias: NX584 | Bootstrap on cold boot (true one-shot)
triggers:
  - event: start
    trigger: homeassistant
actions:
  - if:
      - condition: template
        value_template: "{{ states(verify_entity) not in ['unknown','unavailable',''] }}"
    then:
      - target:
          entity_id: input_boolean.nx584_boot_fix_attempted
        action: input_boolean.turn_off
      - stop: Entity healthy
  - if:
      - condition: template
        value_template: |
          {{ states(verify_entity) in ['unknown','unavailable','']
             and is_state('input_boolean.nx584_boot_fix_attempted','off') }}
    then:
      - target:
          entity_id: input_boolean.nx584_boot_fix_attempted
        action: input_boolean.turn_on
      - action: hassio.addon_restart
        data:
          addon: "{{ addon_slug }}"
      - delay: "00:00:30"
      - action: homeassistant.restart
      - stop: Attempted fix
  - data:
      name: NX584 bootstrap
      message: |
        {{ verify_entity }} still unavailable after one restart attempt.
    action: logbook.log
mode: single
variables:
  verify_entity: binary_sensor.patio_util_door
  addon_slug: 7d607105_nx584

```
